import { useEffect, useState, type ReactNode } from 'react'
import { Alert, Button, Card, Group, SimpleGrid, Stack, Text, Title } from '@mantine/core'
import { toast } from 'sonner'
import { useCreateProject, useDeleteProject, useProjects, useSaveProject } from '../../queries'
import type { Project, ProjectDraft } from '../../types'
import { ProjectCard } from './ProjectCard'
import { ProjectModal } from './ProjectModal'
import './projects.css'
export function ProjectsView({ onHeaderActionChange }: { onHeaderActionChange: (action: ReactNode) => void }) { const [modal, setModal] = useState<'new' | Project | null>(null); const { data: projects = [], error } = useProjects(); const create = useCreateProject(); const save = useSaveProject(); const remove = useDeleteProject(); useEffect(() => { onHeaderActionChange(<Button variant="gradient" onClick={() => setModal('new')}>New project</Button>); return () => onHeaderActionChange(null) }, [onHeaderActionChange]); const submit = async (draft: ProjectDraft) => { if (modal === 'new') { await create.mutateAsync(draft); toast.success('Project created') } else if (modal) { await save.mutateAsync({ project: modal, draft }); toast.success('Project updated') }; setModal(null) }; const deleteProject = (project: Project) => { if (!window.confirm(`Delete project "${project.Title}"? Its tasks will no longer be available.`)) return; remove.mutate(project.ID, { onSuccess: () => toast.success('Project deleted'), onError: (err) => toast.error(err.message) }) }; return <Stack gap="lg">{error && <Alert color="red" title="Unable to load data">{error.message}</Alert>}<section aria-label="Projects"><Group className="section-heading" justify="space-between" align="flex-end" mb="md"><div><Text className="section-eyebrow" size="xs" tt="uppercase">Workspace</Text><Title order={2}>Projects</Title><Text c="dimmed" mt={5}>Keep your delivery work grouped, visible, and moving.</Text></div><Text className="section-count" size="sm" c="dimmed">{projects.length} {projects.length === 1 ? 'project' : 'projects'}</Text></Group>{projects.length === 0 ? <Card className="empty-state" withBorder padding="xl"><Text fw={650}>No projects yet</Text><Text c="dimmed" size="sm" mt={5}>Create your first project to start organizing tickets.</Text></Card> : <SimpleGrid cols={{ base: 1, sm: 2, lg: 3 }}>{projects.map((project) => <ProjectCard key={project.ID} project={project} onEdit={setModal} onDelete={deleteProject} />)}</SimpleGrid>}</section>{modal && <ProjectModal key={modal === 'new' ? 'new' : modal.ID} project={modal === 'new' ? null : modal} onSubmit={submit} onClose={() => setModal(null)} />}</Stack> }
