import { useState, type FormEvent } from 'react'
import { Alert, Button, Group, Modal, Select, Stack, Text, Textarea, TextInput } from '@mantine/core'
import { modalClassNames } from '../shared'
import { COLOR_SWATCHES, DEFAULT_PROJECT_COLOR } from '../colors'
import { STATUSES, STATUS_LABELS, type Project, type ProjectDraft, type Status } from '../../types'
export function ProjectModal({ project, onSubmit, onClose }: { project: Project | null; onSubmit: (draft: ProjectDraft) => Promise<void>; onClose: () => void }) {
  const [title, setTitle] = useState(project?.Title ?? ''); const [description, setDescription] = useState(project?.Description ?? ''); const [status, setStatus] = useState<Status>(project?.Status ?? 'backlog'); const [color, setColor] = useState(project?.Color ?? DEFAULT_PROJECT_COLOR); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null)
  const handleSubmit = (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(null); onSubmit({ Title: title.trim(), Description: description.trim(), Status: status, Color: color }).catch((err: Error) => { setError(err.message); setSubmitting(false) }) }
  return <Modal opened onClose={onClose} title={project ? 'Edit project' : 'New project'} centered size="lg" radius="lg" classNames={modalClassNames} overlayProps={{ backgroundOpacity: 0.65, blur: 3 }}><form onSubmit={handleSubmit}><Stack gap="sm"><TextInput label="Name" value={title} onChange={(event) => setTitle(event.currentTarget.value)} required autoFocus /><Textarea label="Description" value={description} onChange={(event) => setDescription(event.currentTarget.value)} minRows={6} autosize /><Select label="Status" value={status} onChange={(value) => setStatus((value ?? 'backlog') as Status)} data={STATUSES.map((value) => ({ value, label: STATUS_LABELS[value] }))} /><Group justify="space-between" align="center" gap="sm" wrap="nowrap"><Text component="label" size="sm" fw={500}>Color</Text><Group gap={6} wrap="nowrap">{COLOR_SWATCHES.map((swatch) => <button key={swatch} type="button" className={`app-color-swatch${swatch === color ? ' app-color-swatch-selected' : ''}`} style={{ background: swatch }} onClick={() => setColor(swatch)} aria-label={`Select color ${swatch}`} />)}</Group></Group>{error && <Alert color="red">{error}</Alert>}<Group className="app-modal-actions" justify="flex-end" pt="md"><Button variant="default" onClick={onClose} disabled={submitting}>Cancel</Button><Button type="submit" loading={submitting} disabled={!title.trim()}>{project ? 'Save changes' : 'Create project'}</Button></Group></Stack></form></Modal>
}
